import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()
  useEffect(() => {
    router.push("/user/login")
  }, [])
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>
    </div>
  )
}
